### PR TITLE
Added the Perform (juggling) skill

### PR DESCRIPTION
**Pull request by spthiessen**
Added the juggling skill for the Juggler archetype of the Bard.

### CODE REVIEW

**Comment by marcus-downing** [comment]
I take it the Juggler archetype needs this? I'll review that first.

If I do accept this, it also needs adding in a whole bunch of other places as well, such as the script for generating a master list of string for translators to work on. Sadly, the project isn't very DRY when it comes to the list of Perform skills.

**Comment by spthiessen** [comment]
I'm sorry, I'm from Canada and I'm not sure what DRY stands for.

**Comment by marcus-downing** [comment]
My fault, that's a bit of programmer's jargon. It stands for "Don't Repeat Yourself". The idea is that, when writing a program where the same value (such as a fixed number or the name of something) is needed in multiple places, you should have one definitive place for it, and all the other places should refer to that one. That way, if you need to change it, you only have to change it once; if you got something wrong and need to fix it, you only need to fix it once; etc. The opposite backronym, WET stands for "Written Every Time".

This project has grown up very organically, though, with bits of it written using all sorts of different programming languages and other tools, so there's no real sharing of information between them. Hence I have the skill lists repeated in a bunch of different places.

**Comment by marcus-downing** [comment]
Looking at the text of the Juggler, I can't find anything that says it needs Perform (juggling) as skill. None of the abilities hang off it. And for the majority of bards, putting ranks into juggling would be wasted (for the purposes of Versatile Performance). So while you're free to write any unique Perform, Profession, Craft and Knowledge skills you wish into the list for your own character, I don't believe this belongs in the main list for everybody.

**Comment by spthiessen** [comment]
I was wondering about that, and I'm fine with it.

Thanks for looking at it.

**Pull request closed without merging**
